### ISSUE TITLE
WorkflowGui : Action edit popup doesnot open ,display this js error Object.clone is not a function

### ISSUE THREAD

**Issue by ghost** [dpfaffenbauer/WorkflowGUI#14]
I downloaded new version Pimcore5.4.2. Then I installed workflowgui by this command (composer require dpfaffenbauer/workflow-gui:^2.0)
================
![workflowgui](https://user-images.githubusercontent.com/19402815/44333160-a591b800-a48b-11e8-99c0-5d77049c8c79.png)

Steps to reproduce
================
Created new state , new statues then new action. When I click on edit button js error display : [Show/hide message details.] TypeError: Object.clone is not a function
[Action edit popup doesnot [open]]

**Comment by dpfaffenbauer** [comment]
pushed a fix, can you install dev-master and try again pls.

**Comment by ghost** [comment]
Please guide me or provide link for dev-master version.Currently  I am working on Pimcore 5.4.2

**Comment by dpfaffenbauer** [comment]
```composer require dpfaffenbauer/workflow-gui:dev-master```

**Comment by ghost** [comment]
now got the error :  Object.extend is not a function

**Comment by ghost** [comment]
any update???

**Comment by dpfaffenbauer** [comment]
no. will try to sort that next week.

**Comment by dpfaffenbauer** [comment]
@AroraVaishali just pushed another change, can you please test again

**Comment by ghost** [comment]
Yes  , now it is working fine.Thanx
